Brucheum/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Brucheum
{
    public class BookController : Controller
    {
        private string apiService = System.Configuration.ConfigurationManager.AppSettings["apiService"];

        public ActionResult MyBooks()
        {
            return View();
        }
        public ActionResult TheBlondJew()
        {
            ViewBag.Service = apiService;
            return View();
        }
        public ActionResult TableOfContents(string bookTitle)
        {
            ViewBag.Title = bookTitle;
            ViewBag.Service = apiService;
            return View();
        }
        public ActionResult Read(string bookTitle, string startingPoint)
        {
            ViewBag.Title = bookTitle;
            ViewBag.Service = apiService;
            return View();
        }
        public ActionResult MyLibrary()
        {
            return View();
        }
        public ActionResult BooksRead()
        {
            return View();
        }
        public ActionResult EditTreePopup(string bookTitle)
        {
            ViewBag.Title = bookTitle;
            ViewBag.Service = apiService;
            return PartialView("_EditTreePopup");
        }
        public ActionResult Write(string bookTitle, string chapterId, string sectionId, string subSectionId)
        {
            ViewBag.BookTitle = bookTitle;
            ViewBag.Service = apiService;
            ViewBag.chapterId = chapterId;
            ViewBag.sectionId = sectionId;
            ViewBag.subSectionId = subSectionId;
            return View();
        }
    }
}

Brucheum/Views/BookXML/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>My Books</h2>


<div class="threeColumnArray">
    <div id="leftColumn">
        put tag tool here
    </div>
    <div id="middleColumn">
    </div>
    <div id="rightColumn">
        put adds here
    </div>
</div>

Brucheum/Views/BookXML/MyBooksXML.cshtml
@{
    ViewBag.Title = "My Books";
}
<style>
    #divMyBooks {
        margin-top: 55px;
        width: 100%;
        display: flex;
        justify-content: center;
        margin-bottom: 95px;
    }
    .divBook {
        float: left;
        margin-right: 70px;
    }
    .bookImage {
        height: 235px;
        width: 210px;
        box-shadow: 5px 4px rgba(128, 128, 128, 0.40);
        cursor: pointer;
    }
    .divLibrayPages {
        font-size: 24px;
        font-family: Georgia, 'Times New Roman', Times, serif;
        text-decoration: underline;
        cursor: pointer;
        margin-left: 200px;
        margin-bottom: 45px;
    }
</style>

<div class="threeColumnArray">
    <div id="leftColumn">
    </div>
    <div id="middleColumn">
        <div class="pageTitle" id="divBooksWriting">Books I am writing</div>
        <div id="divMyBooks">
            <div class="divBook" book="The Blond Jew">
                <img class="bookImage" src="~/Images/Books/TheBlondJew.jpg" />
            </div>
            <div class="divBook" book="Time Squared">
                <img class="bookImage" src="~/Images/Books/TimeSquared.jpg" />
            </div>
            <div class="divBook" book="Ready; Fire; Aim">
                <img class="bookImage" src="~/Images/Books/ReadyFireAim.jpg" />
            </div>
        </div>
        <div class="divLibrayPages" id="divBooksRead">Books I have Read</div>
        <div class="divLibrayPages" id="divBooksIOwn">Book I Own</div>
    </div>
    <div id="rightColumn">
    </div>
</div>

<script>    
    $('.divBook').click(function () {
        var url = '@Url.Action("TableOfContents", "Book", new { bookTitle = "REPLACEME" })';
        window.location.href = url.replace('REPLACEME', $(this).attr("book"));
    });
</script>

Brucheum/Views/BookXML/ToCXML.cshtml
<link href="~/Styles/tableofContents.css" rel="stylesheet" />

<div class="threeColumnArray">
    <div id="leftColumn"></div>
    <div id="middleColumn">
        <div class="pageTitle" id="divBookTitle">@ViewBag.Title</div>
        <div id="divStatusMessage"></div>
        <div id="divTableOfContents"></div>
        <div id="modalContainer" class="modalVail">
            <div id="modalContent"></div>
        </div>
    </div>
    <div id="rightColumn">
        <div id="divEdit">edit</div>
    </div>
</div>

<script>
    var service = '@ViewBag.Service';

    $(document).ready(function () {
        getTableOfContents();
        resizePage();
     });

    $("#divBookTitle").click(function () {
        var url = '@Url.Action("Read", "Book", new { bookTitle = "REPLACEME" , startingPoint = 0})';
        window.location.href = url.replace('REPLACEME', '@ViewBag.Title');
    });

    $('#divEdit').click(function () {
        $.ajax({
            type: "get",
            url: "/Book/EditTreePopup?bookTitle=" + '@ViewBag.Title',
            datatype: "json",
            success: function (data) {
                $('#modalContent').html(data);
                $('#modalContainer').show();
            },
            error: function (xhr, textStatus, error) {
                displayStatusMessage("error", "status: " + textStatus + "text: " + xhr.statusText + "error: " + error);
                alert("status: " + textStatus + "text: " + xhr.statusText + "error: " + error);
            }
         });
     });

    function getTableOfContents() {
        try {
            $.ajax({
                url: service + "/api/Book/Get?BookTitle=" + '@ViewBag.Title',
                type: "get",
                //dataType: "json",
                success: function (response) {

                    var json = JSON.parse(response);

                    var content = "";
                    try {
                        $.each(json.Book.Chapter, function (idx, objChapter) {
                            content += `<div class='divChapter' Id='` + objChapter.Id + `'>
                            <div class='chapterName'>` + objChapter.Title + `</div>
                            <div class='dots'></div>
                            <div class='divCaret'><img src='/Images/downCaret.png'></div>`;
                            content += "</div>";  // chapter
                            content += "<div class='divSections'>";

                            $.each(objChapter.Section, function (idx, objSection) {
                                if (objSection.Title !== undefined) {
                                    content += "<div class='divSection' Id='" + objSection.Id + "'>" + objSection.Title + "</div>";
                                    content += "<div class='divSubsections'>";
                                    if (objSection.SubSection !== undefined) {
                                        $.each(objSection.SubSection, function (idx, objSubSection) {
                                            if (objSubSection.Title !== undefined) {
                                                content += "<div class='divSubSection' Id='" + objSubSection.Id + "'>" + objSubSection.Title + "</div>";
                                            }
                                        });
                                    }
                                    content += "</div>";  //  divSubsections
                                }
                            });
                            content += "</div>";  // divSections
                        });
                        $("#divTableOfContents").html(content);

                        resizePage();

                        $('.divChapter').click(function () {
                            //$('.divSections').hide();
                            //alert("children : " + $(this).children(2).attr("src"));
                            if ($(this).children(0).children(0).attr("src") === "../../Images/upCaret.png") {
                                $(this).children(0).children(0).attr("src", "../../Images/downCaret.png");
                            }
                            else {
                                $(this).next().show();
                                //alert("next: " + $(this).next());
                                $('.divChapter').children(0).children(0).attr("src", "../../Images/downCaret.png");
                                $(this).children(0).children(0).attr("src", "../../Images/upCaret.png");
                            }
                        });

                        $('.divSection').click(function () {
                            alert("section: " + $(this).attr("Id"));
                        });
                        $('.divSubSection').click(function () {
                            alert("subsection: "+$(this).attr("Id"));
                        });
                        $('.divChapter').dblclick(function () {
                            alert("chapter: " + $(this).attr("Id"));
                        });

                    } catch (e) {
                        alert("catch: "  + e);
                    }
                },
                error: function (xhr) {
                    displayStatusMessage("error", "error: " + xhr.statusText);
                    alert("get table of contents error: " + xhr.statusText);
                }
            });
        }
        catch (e) {
            alert("nice try: "  + e);
        }
    }

</script>

Brucheum/Views/BookXML/WriteXML.cshtml
@{
    ViewBag.Title = "Write " + @ViewBag.BookTitle;
}

<link href="~/Styles/bookEdit.css" rel="stylesheet" />

@*<link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">*@
<link href="~/Styles/quill.snow.css" rel="stylesheet" />
<script src="//cdn.quilljs.com/1.3.6/quill.js"></script>

<style>
    #middleColumn {
        background-color: #eae1ae;
    }

    #divQuillContainer {
        background-color: #fff;
        margin-left: 5px;
        margin-right: 5px;
        margin-bottom: 5px;
        display: block;
    }

    #divEdit {
        margin-top: 10px;
        margin-left: 10px;
        text-decoration: underline;
        cursor: pointer;
    }

    h2 {
        padding-left: 6px;
    }

    .ql-editor {
        z-index: 0;
    }
</style>

<div class="threeColumnArray">
    <div id="leftColumn">
    </div>
    <div id="middleColumn">
        <div class="pageTitle" id="divPageTitle">Edit @ViewBag.BookTitle</div>
        <div class="addEditArea">
            <span>Chapter:</span><div><input class="roundedInput" id="txtChapter" /></div>
            <span>Order:</span><div><input class="roundedInput" id="txtOrder" /></div><br />
            <span>Section:</span><div><input class="roundedInput" id="txtSection" /></div><br />
            <span>Subsection:</span><div><input class="roundedInput" id="txtSubSection" /></div><br />
        </div>
        <div id="divQuillContainer">
            <div id="divQuilleditor"></div>
        </div>
        <div id="divStatusMessage"></div>
        <div id="divButtons">
            <button class="roundendButton" id="btnSave">Save</button>
            <button class="roundendButton" id="btnNew">New Chapter</button>
            <button class="roundendButton" id="btnNewSection">New Section</button>
            <button class="roundendButton" id="btnNewSubSection">New SubSection</button>
        </div>
    </div>
    <div id="rightColumn">
        <div id="divEdit">change section</div>
    </div>
</div>

<script>
    var service = '@ViewBag.Service';
    var article = new Object();
    article.BookTitle = '@ViewBag.BookTitle';
    var quill = new Quill('#divQuilleditor', { theme: 'snow'  });

    $(document).ready(function () {

        if ('@ViewBag.chapterId' !== "") {
            getChapter();
        }

        //var queryString = "?bookTitle=" + '@ViewBag.BookTitle' + "&chapterId=" + '@ViewBag.chapterId' + "&sectionId=" + '@ViewBag.sectionId' + "&subSectionId=" + '@ViewBag.subSectionId';



        resizeEditor();
        $('#btnNew').hide();
        $('#btnNewSection').hide();
        $('#btnNewSubSection').hide();
    });

    $(window).resize(function () {
        alert("WRITE window resize");
        resizeEditor();
     });

    function resizeEditor() {
        var p = $('#txtSubSection').position().top + 154;
        $('#divQuilleditor').height($(window).height() - p);

        var w = $('.addEditArea').width();

        $('#txtChapter').width(w - 300);
        $('#txtSection').width(w - 200);
        $('#txtSubSection').width(w - 200);
        resizePage();
    }

    function bind() {
        $('#txtChapter').val(article.ChapterTitle);
        $('#txtOrder').val(article.ChapterOrder);
        $('#txtSection').val(article.SectionTitle);
        $('#txtSubSection').val(article.SubSectionTitle);
        //quill.root.innerHTML = article.Contents;
        $('.ql-editor').html(article.Contents);
    }

    function unBind() {
        article.Id = $('#hiddenId').val();
        article.ChapterTitle = $('#txtChapter').val();
        article.ChapterOrder = $('#txtOrder').val();
        article.SectionTitle = $('#txtSection').val();
        article.SubSectionTitle = $('#txtSubSection').val();
        article.Contents = $('.ql-editor').html(); // quill.root.innerHTML;
    }


    function post() {
        try {
            unBind();
            $.ajax({
                url: service + "/api/Book",
                type: "post",
                dataType: "Json",
                data: article,
                success: function (result) {
                    if (result.success === "ok") {
                        article.ChapterId = result.ChapterId;
                        article.SectionId = result.SectionId;
                        article.SubSectionId = result.SubSectionId;
                        $('#btnSave').text("Update");
                        $('#btnNew').show();
                        $('#btnNewSection').show();
                        $('#btnNewSubSection').show();
                        displayStatusMessage("ok", "Saved");
                    }
                    else {
                        displayStatusMessage("error", "server ERROR: " + result.success);
                        alert("server ERROR: " + result.success);
                    }
                },
                error: function (xhr) {
                    displayStatusMessage("error", "error: " + xhr.statusText);
                    alert("Post book error: " + xhr.statusText);
                }
             });
        } catch (e) {
            displayStatusMessage("error", "catch ERROR: "  + e);
            alert("catch ERROR: "  + e);
        }
    }

    function put() {
        try {
            unBind();
            $.ajax({
                url: service + "/api/Book",
                type: "put",
                dataType: "json",
                data: article,
                success: function (result) {
                    if (result.success === "ok") {
                        article.SubSectionId = result.SubSectionId;
                        article.SectionId = result.SectionId;
                        displayStatusMessage("ok", "Saved");
                        $('#btnSave').text("Update");
                        $('#btnNew').show();
                        $('#btnNewSection').show();
                        $('#btnNewSubSection').show();
                    }
                    else {
                        displayStatusMessage("error", result.success);
                    }
                },
                error: function (xhr) {
                    displayStatusMessage("error", "error: " + xhr.statusText);
                    alert("Write PUT error: " + xhr.statusText);
                }
            });
        } catch (e) {
            displayStatusMessage("error", "ERROR"  + e);
        }
    }

    $('#btnNew').click(function () {
        article.ChapterOrder = "";
        article.ChapterId = "";
        article.ChapterTitle = "";
        article.SectionId = "";
        article.SectionTitle = "";
        article.SubSectionId = "";
        article.SubSectionTitle = "";
        article.Contents = "  ";
        bind();
        $('#btnSave').text("Save");
        $('#btnNew').hide();
        $('#btnNewSection').hide();
        $('#btnNewSubSection').hide();
     });

    $('#btnNewSection').click(function () {
        article.SectionId = "";
        article.SubSectionId = "";
        article.SubSectionTitle = "";
        article.SectionTitle = "";
        article.Contents = "  ";
        $('#btnSave').text("Add Section");
        $('#btnNew').hide();
        $('#btnNewSection').hide();
        $('#btnNewSubSection').hide();
        bind();
     });

    $('#btnNewSubSection').click(function () {
        article.SubSectionId = "";
        article.SubSectionTitle = "";
        article.Contents = "";
        $('#btnSave').text("Add Sub Section");
        $('#btnNew').hide();
        $('#btnNewSection').hide();
        $('#btnNewSubSection').hide();
        bind();
     });

    $('#divEdit').click(function () {
        $.ajax({
            type: "get",
            url: "/Book/EditTreePopup?bookTitle=" + '@ViewBag.BookTitle',
            datatype: "json",
            success: function (data) {
                $('#modalContent').html(data);
                $('.ql-editor p').hide();
                $('#modalContainer').show();
            },
            error: function (xhr, textStatus, error) {
                displayStatusMessage("error", "status: " + textStatus + "text: " + xhr.statusText + "error: " + error);
                alert("status: " + textStatus + "text: " + xhr.statusText + "error: " + error);
            }
        });
     });

    $('#btnSave').click(function () {
        if ($('#btnSave').text() === "Save")
            post();
        else
            put();
     });

    $('#btnDelete').click(function () {
        if (confirm("Delete " + $('#Title').val() + "?")) {
            try {
                $.ajax({
                    url: webApiURL + "?Id=" + $('#hiddenId').val(),
                    type: "delete",
                    success: function (list, textstatus, xhr) {
                        displayStatusMessage("ok", "entry deleted");
                        window.location = "ArticleList";
                    },
                    error: function (xhr) {
                        displayStatusMessage("error", "error: " + xhr.statusText);
                        alert("delete write error: " + xhr.statusText);
                    }
                 });
            } catch (e) {
                displayStatusMessage("error", "tERROR"  + e);
            }
        }
     });

</script>

Brucheum/Views/BookXML/_EditTreePopup.cshtml
<link href="~/Styles/modalDialog.css" rel="stylesheet" />


<<style>
    #divPopupContainer {
        position: absolute;
        top: 8%;
        left: 35%;
        box-sizing: content-box;
        color: #242729;
        /*width: 280px;*/
        padding: 30px;
        /*border: 1px solid #e4e6e8;*/
        background: #fff;
        z-index: 999;
        min-width: 500px;
    }
    li {
        cursor: pointer;
        text-decoration: underline;
        margin-bottom: 4px;
    }
    .dialogHeader {
        color: purple;
        font-style: oblique;
    }
    #divBookTitle {
        text-align: center;
        font-size: 24px;
        cursor: pointer;
        text-decoration: underline;
    }
    #editTable li {
        text-decoration: underline;
        color: purple;
        cursor: pointer;
        padding: 4px;
    }
</style>

 <div id="divPopupContainer">
     <div id="divStatusMessage"></div>
     <div class="dialogHeader">
         <div id="divBookTitle">@ViewBag.Title</div>
         <span>Choose a Section to edit</span>
         <div id="btnClose" class="divCloseButton">
             <img height="19" src="~/Images/powerOffRed01.png" />
         </div>
     </div>
     <div style="clear:both"></div>

     <div id="divEditTree"></div>
 </div>

<script>
    var service = '@ViewBag.Service';

    $(document).ready(function () {
        loadEditTable();
     });
    $('#btnClose').click(function () {
        clearModal();
     });
        
    $('#divBookTitle').click(function () {
        window.location.href = "Write?bookTitle=" + '@ViewBag.Title' + "&chapterId=null&sectionId=null&subSectionId=null";
        clearModal();
    });

    function loadEditTable() {
        try {
            $.ajax({
                url: service + "/api/Book/Get?BookTitle=" + '@ViewBag.Title',
                type: "get",
                success: function (response) {
                    try {
                        var json = JSON.parse(response);
                        var content = "<div id='editTable'><ul>";
                        $.each(json.Book.Chapter, function (idx, chapter) {
                            content += "<li chapter='" + chapter.Id + "'>" + chapter.Title + "</li><ul>";

                            //alert("content: " + content);
                            if (chapter.Section !== undefined) {
                                $.each(chapter.Section, function (idx, section) {
                                    if (section.Title !== undefined) {
                                        content += "<li chapter='" + chapter.Id + "' section='" + section.Id + "'>" + section.Title + "</li><ul>";
                                        if (section.SubSection !== undefined) {
                                            $.each(section.SubSection, function (idx, subSection) {
                                                if (subSection.Title !== undefined) {
                                                    content += "<li chapter='" + chapter.Id + "' section='" + section.Id + "' subsection='" + subSection.Id + "'>" + subSection.Title + "</li>";
                                                    //alert("subsection: " + content);
                                                }
                                            })
                                        }
                                        content += "</ul>";
                                    }
                                });
                            }
                            content += "</ul>";
                        });
                        content += "</div>";
                        //alert("content: " + content);

                        $("#divEditTree").html(content);

                        $("li").click(function () {
                            window.location.href = "Write?bookTitle=" + '@ViewBag.Title' + "&chapterId=" + $(this).attr("chapter") + "&sectionId=" + $(this).attr("section") + "&subSectionId=" + $(this).attr("subSection");
                        });

                    } catch (e) {
                        alert("getEditTable catch: " + e);
                    }
                },
                error: function (xhr) {
                    displayStatusMessage("error", "error: " + xhr.statusText);
                    alert("load edit table PUT error: " + xhr.statusText);
                }
            });
        }
        catch (e) {
            alert("nice try: " + e);
        }
    }

</script>